### ISSUE TITLE
Create Hello World

### ISSUE THREAD

**Issue by kimberlih** [kimberlih/Schoolsheet#1]
Create an Rails API project that will run on **Ruby 2.5** and **Rails 5x**.

Database needs to be **postgresql**.

Need to get a Home Page up that return Hello World.

**Comment by kimberlih** [comment]
How to setup rails with Docker:

1. [install Compose](https://docs.docker.com/compose/install/).

2 Create the Rails `Dockerfile`

```dockerfile
# syntax=docker/dockerfile:1
FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN bundle install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
```

# 3. Create `Gemfile`

```ruby
source 'https://rubygems.org'
gem 'rails', '~>5'
```

# 4. Create empty `Gemfile.lock`.

```console
$ touch Gemfile.lock
```

# 5. Script to enable server restart when a `server.pid` file pre-exists.
This script will be executed every time the container gets started.
`entrypoint.sh` consists of:

```bash
#!/bin/bash
set -e

# Remove a potentially pre-existing server.pid for Rails.
rm -f /myapp/tmp/pids/server.pid

# Then exec the container's main process (what's set as CMD in the Dockerfile).
exec "$@"
```

# 6. Create the `docker-compose.yml` file that will run the Rails and Postgres systems.

```yaml
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
```

# 7. Build the project

```console
$ docker compose run --no-deps web rails new . --force --database=postgresql
```

First, Compose builds the image for the `web` service using the `Dockerfile`.
The `--no-deps` tells Compose not to start linked services. Then it runs
`rails new` inside a new container, using that image. Once it's done, you
should have generated a fresh app.

On Linux
```console
$ sudo chown -R $USER:$USER .
```

# 8. Build again after gemfile update

```console
$ docker compose build
```

# 9. Connect the database

Replace the contents of `config/database.yml` with the following:

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
```

# 10. Run docker compose up to start the rails and psql server.

```console
$ docker compose up
```

# 11. Create the database. In another terminal, run:

```console
$ docker compose run web rake db:create
```

# Stop the application

```console
$ docker compose down
```

# Restart the application

To restart the application run `docker compose up` in the project directory.

# Rebuild the application

If you make changes to the Gemfile or the Compose file to try out some different
configurations, you need to rebuild. Some changes require only
`docker compose up --build`, but a full rebuild requires a re-run of
`docker compose run web bundle install` to sync changes in the `Gemfile.lock` to
the host, followed by `docker compose up --build`.
